content:
  - name: works
    label: Works
    path: src/data/works
    type: collection
    filename: '{fields.title}.md'
    view:
      fields: [heroImage, title, pubDate]
    fields:
      - name: published
        label: Is Published
        type: boolean
        default: true
      - name: pubDate
        label: Publication Date
        type: date
        options:
          format: MMM dd yyyy
      - name: title
        label: Title
        type: string
      - name: body
        label: Body
        type: rich-text
      - name: heroImage
        label: Hero Image
        type: image
      - name: attachments
        label: Attachments
        type: image
        options:
          multiple:
            max: 10
  - name: videos
    label: Videos
    path: src/data/videos
    type: collection
    filename: '{fields.title}.md'
    view:
      fields: [heroImage, title, pubDate]
    fields:
      - name: published
        label: Is Published
        type: boolean
        default: true
      - name: pubDate
        label: Publication Date
        type: date
        options:
          format: MMM dd yyyy
      - name: title
        label: Title
        type: string
      - name: body
        label: Body
        type: rich-text
      - name: link
        label: Link
        type: string
  - name: music
    label: Music
    path: src/data/music
    type: collection
    filename: '{fields.title}.md'
    view:
      fields: [heroImage, title, pubDate]
    fields:
      - name: published
        label: Is Published
        type: boolean
        default: true
      - name: pubDate
        label: Publication Date
        type: date
        options:
          format: MMM dd yyyy
      - name: title
        label: Title
        type: string
      - name: artist
        label: Artist
        type: string
      - name: body
        label: Body
        type: rich-text
      - name: heroImage
        label: Hero Image
        type: image
      - name: embed-code
        label: Embed Code
        type: string
      - name: type
        label: Type
        type: select
        options:
          values: [ spotify, apple, soundcloud ]
media:
  - name: files
    label: Files
    input: source-image
    output: source-image
    categories: [ jpg ]