content:
  - name: works
    label: Works
    path: src/data/works
    type: collection
    filename: '{fields.title}.md'
    view:
      fields: [heroImage, title, pubDate]
    fields:
      - name: published
        label: Is Published
        type: boolean
        default: true
      - name: pubDate
        label: Publication Date
        type: date
        options:
          format: MMM dd yyyy
      - name: title
        label: Title
        type: string
      - name: body
        label: Body
        type: rich-text
      - name: heroImage
        label: Hero Image
        type: image
      - name: attachments
        label: Attachments
        type: image
        options:
          multiple:
            max: 10
  - name: music
    label: Music
    path: src/data/music
    type: collection
    filename: '{fields.title}.md'
    view:
      fields: [title, pubDate]
    fields:
      - name: published
        label: Is Published
        type: boolean
        default: true
      - name: pubDate
        label: Publication Date
        type: date
        options:
          format: MMM dd yyyy
      - name: title
        label: Title
        type: string
      - name: body
        label: Body
        type: rich-text
      - name: embedCode
        label: Embed Code
        type: string
      - name: type
        label: Type
        type: select
        options:
          values: [ youtube, spotify, soundcloud, bandcamp ]
  - name: pages
    label: Pages
    path: src/data/pages
    type: collection
    filename: '{fields.title}.md'
    view:
      fields: [heroImage, title, pubDate]
    fields:
      - name: published
        label: Is Published
        type: boolean
        default: true
      - name: pubDate
        label: Publication Date
        type: date
        options:
          format: MMM dd yyyy
      - name: title
        label: Title
        type: string
      - name: body
        label: Body
        type: rich-text
media:
  - name: files
    label: Files
    input: public/images
    output: public/images
    categories: [ jpg, webp, png ]